Use tokens on gcs to validate requests
GoogleCloudPlatform/google-cloud-gemserver pull request #28
Opened 2017-08-03 21:47 UTC by arhamahmed

Fixes #27.

The new authentication flow is to create a token that gets uploaded to GCS and appended to every request. The server checks if the token file exists and its value matches the token in the request for the request to succeed. The token files are unique so concurrent requests are not an issue.

2017-08-04 00:16 UTC, hxiong388 approved these changes

2017-08-04 01:04 UTC, dazuma requested changes
I think we need to rework this strategy. This allows anyone with GCS read access to steal credentials in flight.

You should be able to simply get an access token on the CLI side (use the googleauth gem), pass that as the Authorization header to the backend, and then validate it on the back end using the tokeninfo API.

2017-08-05 06:55 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          res.code.to_i == 200
I take it this is checking that the token is valid, but we need to check the roles assigned, that the token grants owner or editor access

2017-08-05 06:57 UTC, dazuma commented on lib/google/cloud/gemserver/cli/request.rb
> +            req.initialize_http_header({"GEMSERVER-CREDENTIALS": t})
Can we just use a standard Authorization header here?

2017-08-05 06:58 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          if ENV["GOOGLE_APPLICATION_CREDENTIALS"]
Are you sure get_application_default doesn't handle this already?

2017-08-06 07:41 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          res.code.to_i == 200
Looking at this more closely, it looks like I didn't get this right either. The tokeninfo call checks the integrity of the token but not its access. Now I'm not sure how to check for certain access. We might need to use the access token to attempt some admin call (like appengine.services.get) and make sure it succeeds. Let's look at this again on Monday.

2017-08-06 15:28 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          res.code.to_i == 200
Another possible option: https://cloud.google.com/iam/docs/testing-permissions

2017-08-06 15:29 UTC, dazuma commented on lib/google/cloud/gemserver/cli/request.rb
> +            req.initialize_http_header({"GEMSERVER-CREDENTIALS": t})
https://github.com/google/signet/blob/master/lib/signet/oauth_2.rb#L120

2017-08-08 17:49 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          eval(res.body)[:split][:allocations].first[0]
eval??

2017-08-08 17:49 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          endpoint = "/v1/apps/#{@proj}/services/default?updateMask=split"
An empty mask didn't work?

2017-08-08 17:50 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          if dom.include? "https"
Ruby style: `http.use_ssl = true if dom.include? "https"`

2017-08-08 17:52 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          tokeninfo_endpoint = "/oauth2/v1/tokeninfo?access_token=#{token}"
Do we even need to call tokeninfo now?

2017-08-08 18:00 UTC, arhamahmed commented on lib/google/cloud/gemserver/authentication.rb
> +          eval(res.body)[:split][:allocations].first[0]
The response was a string but formatted as a hash, eval was to convert it to a hash.

2017-08-08 18:03 UTC, arhamahmed commented on lib/google/cloud/gemserver/authentication.rb
> +          endpoint = "/v1/apps/#{@proj}/services/default?updateMask=split"
No, an empty mask implies the update applies to all fields.

2017-08-08 18:07 UTC, arhamahmed commented on lib/google/cloud/gemserver/authentication.rb
> +          tokeninfo_endpoint = "/oauth2/v1/tokeninfo?access_token=#{token}"
We can remove it, appengine implicitly validates the token.

2017-08-08 18:12 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +          eval(res.body)[:split][:allocations].first[0]
Is it JSON? (I assume it's not actually a Ruby hash.) Can we just use a JSON parser? Eval is dangerous.

2017-08-08 21:47 UTC, dazuma commented on lib/google/cloud/gemserver/authentication.rb
> +require "securerandom"
Is securerandom still used?

2017-08-08 21:48 UTC, dazuma approved these changes

2017-08-08 21:59 UTC, merged